server:
  port: 8082
  servlet:
    context-path: /myblog
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.170.55:3306/myblog
    username: root
    password: root
  resources:
    static-locations: classpath:/static/
mybatis:
  type-aliases-package: com.spring.fastdfs.pojo
  mapper-locations: classpath:mappers/*.xml